### ISSUE TITLE
What is this mod doing??

### ISSUE THREAD

**Issue by border999** [Minecraft-LightLand/Youkai-Homecoming#1]
https://gist.github.com/border999/4b343bea1155c05b81fa9c9202990e2c
this issue doesn't occur when Youkai is not installed. Failure to validate causes the issue of mods that are in my mods list not being seen and so their dependets list them as missing.

**Comment by lcy0x1** [comment]
This mod requires Registrate 1.3.11, but Tome of Blood requires exactly Registrate 1.3.3.

I will try if lower version works, but please report to their issues that they are being too strict about Registrate versions
