### ISSUE TITLE
[Suggestion] Split the non-food stuff into a separate mod

### ISSUE THREAD

**Issue by emihead** [Minecraft-LightLand/Youkai-Homecoming#10]
Hi, sorry if this is rude but I would love the option to have the new food items without having all the other Touhou stuff to worry about. If there's any food that depends on those other mechanics then you could maybe only load them when both mods are installed.
Full disclosure, I'm not much of a Touhou fan, but I liked the idea of being able to have more unique crops and food items, since this mod adds a lot. But the other stuff really makes the mod a lot more broad and less applicable as just a Farmer's Delight addon. I don't think it would hurt to just split the mod up into 2 and have them be integrated with one another when both are installed. Again, I hope this doesn't come off as rude, this comes from a desire to be able to use these food items in a way that's more applicable to my modpack, since they look really interesting.

**Comment by lcy0x1** [comment]
all of those can be disabled in config.

Splitting is already done for 1.21 but I don't want to destroy existing players' saves by removing contents from 1.20.1.
