### ISSUE TITLE
BUFF冲突导致的服务端关闭/崩溃（服务端连接丢失）？

### ISSUE THREAD

**Issue by SakuraRK** [Minecraft-LightLand/Youkai-Homecoming#3]
在食用带有清醒BUFF的食物后，再食用会增加“妖怪化”相关的食物，有概率会导致游戏内部服务端崩溃。

[2024-06-13-2.log.gz](https://github.com/user-attachments/files/15838708/2024-06-13-2.log.gz)
[debug-2.log.gz](https://github.com/user-attachments/files/15838710/debug-2.log.gz)
[2024-06-14-1.log.gz](https://github.com/user-attachments/files/15838711/2024-06-14-1.log.gz)
[debug-1.log.gz](https://github.com/user-attachments/files/15838712/debug-1.log.gz)
已附带可能的日志

**Comment by lcy0x1** [comment]
什么版本？我记得很早就处理过这个问题了

**Comment by SakuraRK** [comment]
好像是2.0.3，但我更新过modpack版本，所以原版本是什么不记得了
但如果这个版本也有问题的话，也请指明一下修复了的版本（尽可能高也行），我也方便和modpack作者报告一下
麻烦了！

**Comment by lcy0x1** [comment]
2.0.3是很早期的版本了，现在想玩可以用最新版2.2.5，修复了很多问题。2.2.6更新之后会修复更多问题，如果没那么急的话可以等2.2.6，不然可以先玩2.2.5
