### ISSUE TITLE
晾干配方与新版JEI冲突

### ISSUE THREAD

**Issue by ZhiyuanQiupan** [Minecraft-LightLand/Youkai-Homecoming#8]
版本：1.20.1
模组版本：2.2.8
使用最新版JEI查看晾干类配方时会发生崩溃
崩溃报告：
[crash-2024-08-07_20.45.04-client.txt](https://github.com/user-attachments/files/16525513/crash-2024-08-07_20.45.04-client.txt)

**Comment by lcy0x1** [comment]
2.2.10修复
