### ISSUE TITLE
建议添加可配置的伤害类型、固定伤害和回血

### ISSUE THREAD

**Issue by nmsl123467** [Minecraft-LightLand/Youkai-Homecoming#9]
boss生物（单指有血条的）无法受到除弹幕类伤害之外的任何伤害，也就是说其他mod的武器完全无效，即使使用该mod的弹幕类型武器也只能造成固定伤害，无论伤害改成多少（例如修改为9999999伤害，boss每次依然只会掉10点血），而且boss的自动回血让战斗更加困难，希望在配置文件中能手动禁用和启用boss是否只能受到弹幕类伤害、boss是否只能受到固定伤害以及是否开启boss回血，一方面能降低难度，也更方便跟其他mod联动
另外还有一个致命bug，boss掉进虚空以后彻底无敌，/kill指令都清不掉，直接损坏存档

**Comment by lcy0x1** [comment]
boss掉进虚空无敌这个问题我会处理，目前你可以把它tp上来kill

其他mod武器也是有效的，但是有伤害限制和更长的伤害冷却

目前boss也就一个灵梦，你可以直接关闭灵梦生成。灵梦不会自动回血。只有弹幕击中不处于妖怪化状态下的目标才会回血。

如果真的不想玩弹幕战，你可以常态妖怪化然后用普通武器磨死。3分钟内能搞定。

其他问题进QQ群谈。群号在mcmod上

**Comment by lcy0x1** [comment]
2.2.12 更新：
- 修复进入虚空无法kill
- 添加配置文件开关非弹幕伤害抗性
- 添加配置文件开关非弹幕伤害额外冷却时间

**Comment by nmsl123467** [comment]
> boss掉进虚空无敌这个问题我会处理，目前你可以把它tp上来kill
> 
> 其他mod武器也是有效的，但是有伤害限制和更长的伤害冷却
> 
> 目前boss也就一个灵梦，你可以直接关闭灵梦生成。灵梦不会自动回血。只有弹幕击中不处于妖怪化状态下的目标才会回血。
> 
> 如果真的不想玩弹幕战，你可以常态妖怪化然后用普通武器磨死。3分钟内能搞定。
> 
> 其他问题进QQ群谈。群号在mcmod上

已经在群里面反馈了，可以看一下我的录屏，配置文件里面回血和伤害限制最好还是添加一下，要不然真的打不过，而且回血机制貌似有bug，只要生成就无限回血，打的还没回的快
